extends: airbnb
plugins:
  - import
rules:
  no-console:
    off
  no-underscore-dangle:
    off
  no-shadow:
    off
  no-unused-vars:
    off
  no-param-reassign:
    off
  max-len:
    off
  consistent-return:
    off
  react/jsx-filename-extension:
    off
  react/prop-types:
    off
  react/react-in-jsx-scope:
    off