dist: trusty
language: node_js
node_js:
  - '8'

services:
  - mongodb

cache:
  directories:
    - 'node_modules'

install:
  - npm install

before_script:
  - sleep 15
  - npm run seed
  - next build
  - next start