const mongoose = require('mongoose');

// The unique ID for a Vote will be MongoDB's default _id, autogenerated.
const commentVoteSchema = mongoose.Schema({
  comment: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Comment',
  }, // Unique ID for the Comment on which this Vote is placed.
  date: {
    type: Date,
    default: Date.now,
  }, // Date for when this Vote was placed.
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
  }, // Unique ID for the User who created/voted this Vote.
  up: Boolean, // If this is true, it's an upvote. If it's false, it's a downvote.
});
