const mongoose = require('mongoose');

// The unique ID for a Comment will be MongoDB's default _id, autogenerated.
const commentSchema = mongoose.Schema({
  parent: Number, // Optional, refers to the parent of the Comment, another Comment.
  author: Number, // Unique ID of the author of the Comment, a User.
  text: String, // Actual text of the comment.
  date: {
    type: Date,
    default: Date.now,
  }, // Datetime of when the Comment was created/reached us.

  // Optional, if not a nested Comment (i.e. a top-level Comment),
  // then it is the unique ID of the Post to which this Comment belongs.
  post: Number,
  upvotes: Number, // Number of upvotes.
  downvotes: Number, // Number of downvotes.
});