const mongoose = require('mongoose');

// The unique ID for a Comment will be MongoDB's default _id, autogenerated.
const commentSchema = mongoose.Schema({
  parent: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Comment',
  }, // Optional, refers to the parent of the Comment, another Comment.
  author: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',    
  }, // Unique ID of the author of the Comment, a User.
  body: String, // Actual text of the Comment.
  date: {
    type: Date,
    default: Date.now,
  }, // Datetime of when the Comment was created/reached us.

  // Optional, if not a nested Comment (i.e. a top-level Comment),
  // then it is the unique ID of the Post to which this Comment belongs.
  post: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Post',    
  },
});
