const mongoose = require('mongoose');

// The unique ID for a Downvote will be MongoDB's default _id, autogenerated.
const downvoteSchema = mongoose.Schema({
  comment: Number, // Unique ID for the Comment on which this Downvote is placed.
  date: {
    type: Date,
    default: Date.now,
  }, // Date for when this Downvote was placed.
  user: Number, // Unique ID for the User who created/voted this Downvote.
  // Sketchy solution below.
  type: String, // e.g. Comment, or Post
});
