const mongoose = require('mongoose');

// The unique ID for a Sub will be MongoDB's default _id, autogenerated.
const subSchema = mongoose.Schema({
  creator: Number, // ID of the User who created this Sub.
  description: String, // Description of the Sub.
  title: {
    type: String,
    unique: true,
  }, // Title of the Sub, serves as the /r/title as well.
  date: {
    type: Date,
    default: Date.now,
  }, // Self-explanatory.
});
