const mongoose = require('mongoose');

// The unique ID for a Upvote will be MongoDB's default _id, autogenerated.
const upvoteSchema = mongoose.Schema({
  comment: Number, // Unique ID for the Comment on which this Upvote is placed.
  date: {
    type: Date,
    default: Date.now,
  }, // Date for when this Upvote was placed.
  user: Number, // Unique ID for the User who created/voted this Upvote.
  // Sketchy solution below.
  type: String, // e.g. Comment, or Post
});
