const mongoose = require('mongoose');

// The unique ID for a upvote will be MongoDB's default _id, autogenerated.
const upvoteSchema = mongoose.Schema({
  comment: Number, // Unique ID for the comment on which this upvote is placed.
  date: {
    type: Date,
    default: Date.now,
  }, // Date for when this upvote was placed.
  user: Number, // Unique ID for the User who created/voted this upvoted.
});