const mongoose = require('mongoose');

// The unique ID for a comment will be MongoDB's default _id, autogenerated.
const commentSchema = mongoose.Schema({
  parent: Number, // Optional, refers to the parent of the comment.
  author: Number, // Unique ID of the author of the comment, a User.
  text: String, // Actual text of the comment.
  date: {
    type: Date,
    default: Date.now,
  }, // Datetime of when the comment was created/reached us.

  // Optional, if not a nested comment (i.e. a top-level comment),
  // then it is the unique ID of the post to which this comment belongs.
  post: Number,
  upvotes: Number, // Number of upvotes.
  downvotes: Number, // Number of downvotes.
});